a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [en, tr]      # [1-a]
    default_locale: en             # [1-b]
    required_locales: [tr]         # [1-c]
    templating: "@A2lixTranslationForm/bootstrap_5_layout.html.twig"      # [2]